framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true

    php_errors:
        log: true

    validation:
        enabled: true
        email_validation_mode: html5

when@test:
    framework:
        test: true
